from setuptools import setup, find_packages

setup(
    name="YOLOv5",
    version="7.0.0",
    author="Glenn Jocher, Ayush Chaurasia, Jing Qiu",
    author_email="contact@ultralytics.com",  # Update with a valid email address
    description="Ultralytics YOLOv5 for SOTA object detection, instance segmentation and image classification.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/ultralytics/yolov5/",
    project_urls={
        "Bug Reports": "https://github.com/ultralytics/yolov5/issues",
        "Funding": "https://ultralytics.com",
        "Source": "https://github.com/ultralytics/yolov5/",
    },
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Image Recognition",
        "Operating System :: POSIX :: Linux",
        "Operating System :: MacOS",
        "Operating System :: Microsoft :: Windows",
    ],
    license="AGPL-3.0",
    python_requires=">=3.8",
    install_requires=[
        "matplotlib>=3.3.0",
        "numpy>=1.22.2",
        "opencv-python>=4.6.0",
        "pillow>=7.1.2",
        "pyyaml>=5.3.1",
        "requests>=2.23.0",
        "scipy>=1.4.1",
        "torch>=1.8.0",
        "torchvision>=0.9.0",
        "tqdm>=4.64.0",
        "psutil",
        "py-cpuinfo",
        "thop>=0.1.1",
        "pandas>=1.1.4",
        "seaborn>=0.11.0",
        "ultralytics>=8.0.232"
    ],
    extras_require={
        "dev": [
            "ipython",
            "check-manifest",
            "pre-commit",
            "pytest",
            "pytest-cov",
            "coverage[toml]",
            "mkdocs-material",
            "mkdocstrings[python]",
            "mkdocs-redirects",
            "mkdocs-ultralytics-plugin>=0.0.34",
        ],
        "export": [
            "onnx>=1.12.0",
            "coremltools>=7.0; platform_system != 'Windows'",
            "openvino-dev>=2023.0",
            "tensorflow<=2.13.1",
            "tensorflowjs>=3.9.0",
        ],
        "logging": [
            "comet",
            "tensorboard>=2.13.0",
            "dvclive>=2.12.0",
        ],
        "extra": [
            "ipython",
            "albumentations>=1.0.3",
            "pycocotools>=2.0.6",
        ],
    },
)
