from setuptools import setup, find_packages

setup(
    name="benjamin",
    version="7.0.0",
    author="Glenn Jocher, Ayush Chaurasia, Jing Qiu",
    description="Ultralytics YOLOv5 for SOTA object detection, instance segmentation and image classification.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/ultralytics/yolov5/",
    project_urls={
        "Bug Reports": "https://github.com/ultralytics/yolov5/issues",
        "Funding": "https://ultralytics.com",
        "Source": "https://github.com/ultralytics/yolov5/",
    },
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Image Recognition",
        "Operating System :: POSIX :: Linux",
        "Operating System :: MacOS",
        "Operating System :: Microsoft :: Windows",
    ],
    license="AGPL-3.0",
    python_requires=">=3.8",
)
